Repository NightscoutFoundation/xDrip, pull requests merged in 2020-12, with the labels that each got.

#1524 Tzachi libre2 support 1
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/eveningoutpost/dexdrip/Home.java
  app/src/main/java/com/eveningoutpost/dexdrip/LibreAlarmReceiver.java
  app/src/main/java/com/eveningoutpost/dexdrip/Models/ActiveBluetoothDevice.java
  app/src/main/java/com/eveningoutpost/dexdrip/Models/JoH.java
  app/src/main/java/com/eveningoutpost/dexdrip/Models/Libre2SensorData.java
  app/src/main/java/com/eveningoutpost/dexdrip/Models/LibreBluetooth.java
  app/src/main/java/com/eveningoutpost/dexdrip/Models/LibreOOPAlgorithm.java
  app/src/main/java/com/eveningoutpost/dexdrip/NFCReaderX.java
  app/src/main/java/com/eveningoutpost/dexdrip/NSEmulatorReceiver.java
  app/src/main/java/com/eveningoutpost/dexdrip/Services/DexCollectionService.java
  app/src/main/java/com/eveningoutpost/dexdrip/Services/LibreWifiReader.java
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/CompatibleApps.java
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/HM10Attributes.java
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/Intents.java
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/LibreUtils.java
  app/src/main/res/layout/activity_enable_bluetooth.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/pref_data_source.xml
Labels: device-libre

#1529 Tzachi cleanup
  app/src/main/java/com/eveningoutpost/dexdrip/Models/BgReading.java
  app/src/main/java/com/eveningoutpost/dexdrip/Models/Sensor.java
  app/src/main/java/com/eveningoutpost/dexdrip/utils/LibreTrendUtil.java
Labels: code

#1499 add templates for bugs and feature requests
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: code

#1498 Stats round percentage
  app/src/main/java/com/eveningoutpost/dexdrip/stats/FirstPageFragment.java
  app/src/main/java/com/eveningoutpost/dexdrip/stats/StatsResult.java
  wear/src/main/java/com/eveningoutpost/dexdrip/stats/StatsResult.java
Labels: ui

#1471 Fix Sensor Battery Broadcast
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/BroadcastGlucose.java
  wear/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/BridgeBattery.java
  wear/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/BroadcastGlucose.java
Labels: bug, sync

#1515 consistent trend arrows
  app/src/main/java/com/eveningoutpost/dexdrip/ImportedLibraries/dexcom/Dex_Constants.java
  app/src/main/java/com/eveningoutpost/dexdrip/Models/BgReading.java
  app/src/test/java/com/eveningoutpost/dexdrip/ImportedLibraries/dexcom/Dex_ConstantsTest.java
  wear/src/main/java/com/eveningoutpost/dexdrip/ImportedLibraries/dexcom/Constants.java
  wear/src/main/java/com/eveningoutpost/dexdrip/Models/BgReading.java
Labels: ui

#1024 widget improvements
  app/src/main/java/com/eveningoutpost/dexdrip/xDripWidget.java
  app/src/main/res/layout/x_drip_widget.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/xdrip_plus_prefs.xml
Labels: enhancement, widget

#1568 add foregroundServiceType to services using Bluetooth
  app/src/main/AndroidManifest.xml
Labels: bluetooth, next-build
