Repository NightscoutFoundation/xDrip, pull requests merged in 2021-05, with the labels that each got.

#1726 Add resource string for the newly added Stop Sensor Confirmation
  app/src/main/java/com/eveningoutpost/dexdrip/StopSensor.java
  app/src/main/res/values/strings.xml
Labels: next-build, translation

#1710 WebService improvements: add treatments endpoint, caching for SGVs
  app/src/main/java/com/eveningoutpost/dexdrip/dagger/Singleton.java
  app/src/main/java/com/eveningoutpost/dexdrip/webservices/RouteFinder.java
  app/src/main/java/com/eveningoutpost/dexdrip/webservices/WebServiceModule.java
  app/src/main/java/com/eveningoutpost/dexdrip/webservices/WebServiceSgv.java
  app/src/main/java/com/eveningoutpost/dexdrip/webservices/WebServiceTreatments.java
  app/src/test/java/com/eveningoutpost/dexdrip/webservices/RouterFinderTest.java
Labels: next-build, sync

#1698 Statistics linebreak
  app/src/main/res/layout/stats_general.xml
  app/src/main/res/xml/xdrip_plus_prefs.xml
Labels: next-build, ui
