Repository NightscoutFoundation/xDrip, pull requests merged in 2021-03, with the labels that each got.

#1660 Update FirmwareCapability.java
  app/src/main/java/com/eveningoutpost/dexdrip/G5Model/FirmwareCapability.java
Labels: device-dexcom-transmitter, enhancement, next-build

#1662 Add a new command 0x08
  app/src/main/java/com/eveningoutpost/dexdrip/Models/Bubble.java
  wear/src/main/java/com/eveningoutpost/dexdrip/Models/Bubble.java
Labels: device-bubble, next-build

#1685 Update FirmwareCapability.java
  app/src/main/java/com/eveningoutpost/dexdrip/G5Model/FirmwareCapability.java
Labels: next-build

#1673 fix: searching 'multi' in preferences and selecting first item will cause exception
  app/src/main/res/xml/xdrip_plus_prefs.xml
Labels: next-build, settings

#1675 add contact to README.md
  README.md
Labels: next-build, type-documentation

#1596 securing Google Maps key
  app/build.gradle
  app/gradle.properties
  app/src/debug/res/values/google_maps_api.xml
  app/src/main/AndroidManifest.xml
  app/src/release/res/values/google_maps_api.xml
Labels: code, next-build, security
