Repository NightscoutFoundation/xDrip, pull requests merged in 2021-06, with the labels that each got.

#1743 Tzachi libre improvements 4
  app/src/main/java/com/eveningoutpost/dexdrip/LibreAlarmReceiver.java
  app/src/main/java/com/eveningoutpost/dexdrip/Models/GlucoseData.java
  app/src/main/java/com/eveningoutpost/dexdrip/Models/JoH.java
  app/src/main/java/com/eveningoutpost/dexdrip/Models/LibreBlock.java
  app/src/main/java/com/eveningoutpost/dexdrip/Models/LibreBluetooth.java
  app/src/main/java/com/eveningoutpost/dexdrip/Models/LibreOOPAlgorithm.java
  app/src/main/java/com/eveningoutpost/dexdrip/Models/PredictionData.java
  app/src/main/java/com/eveningoutpost/dexdrip/Models/ReadingData.java
  app/src/main/java/com/eveningoutpost/dexdrip/NFCReaderX.java
  app/src/main/java/com/eveningoutpost/dexdrip/NSEmulatorReceiver.java
  app/src/main/java/com/eveningoutpost/dexdrip/Services/LibreWifiData.java
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/LibreUtils.java
  app/src/main/java/com/eveningoutpost/dexdrip/utils/LibreTrendGraph.java
  app/src/main/java/com/eveningoutpost/dexdrip/utils/LibreTrendPoint.java
  app/src/main/java/com/eveningoutpost/dexdrip/utils/LibreTrendUtil.java
  app/src/test/java/com/eveningoutpost/dexdrip/Models/ReadingDataTest.java
  wear/src/main/java/com/eveningoutpost/dexdrip/Models/PredictionData.java
  wear/src/main/java/com/eveningoutpost/dexdrip/Models/ReadingData.java
  wear/src/main/java/com/eveningoutpost/dexdrip/NFCReaderX.java
Labels: device-libre

#1723 update rxandroidble2 to 1.12.1
  app/build.gradle
  app/src/main/java/com/eveningoutpost/dexdrip/utils/bt/ScanRecordFromLegacy.java
  app/src/main/java/com/eveningoutpost/dexdrip/utils/bt/ScanRecordImplCompatLocal.java
  wear/build.gradle
Labels: bluetooth, next-build

#1718 Improve Tasker snooze functionality
  app/src/main/java/com/eveningoutpost/dexdrip/SnoozeActivity.java
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/AlertPlayer.java
  app/src/main/java/com/eveningoutpost/dexdrip/localeTasker/receiver/FireReceiver.java
Labels: next-build, ux-alarm

#1731 Change Nightscout "Download data" to "Download treatments"
  app/src/main/res/values/strings.xml
Labels: next-build, settings

#224 If all alerts are disabled, do not alert for low bridge battery.
  app/src/main/java/com/eveningoutpost/dexdrip/utils/CheckBridgeBattery.java
Labels: next-build, ux-notification

#1747 Exclude Nightscout ID and password from logs
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/NightscoutUploader.java
Labels: logging, next-build, security

#1096 Ask for re-transmission in the case that some packets have been lost.
  app/src/main/java/com/eveningoutpost/dexdrip/Models/Tomato.java
  app/src/main/java/com/eveningoutpost/dexdrip/Services/DexCollectionService.java
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/BridgeResponse.java
Labels: device-miaomiao, enhancement, next-build

#1761 interprete only 344 bytes for Libre2 FRAM NFC data
  app/src/main/java/com/eveningoutpost/dexdrip/Models/Bubble.java
  app/src/main/java/com/eveningoutpost/dexdrip/Models/LibreBlock.java
  app/src/main/java/com/eveningoutpost/dexdrip/Models/LibreOOPAlgorithm.java
  app/src/main/java/com/eveningoutpost/dexdrip/Models/Tomato.java
  app/src/main/java/com/eveningoutpost/dexdrip/NFCReaderX.java
  app/src/main/java/com/eveningoutpost/dexdrip/Services/DexCollectionService.java
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/Blukon.java
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/Constants.java
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/LibreUtils.java
  app/src/main/java/com/eveningoutpost/dexdrip/utils/LibreTrendPoint.java
  app/src/main/java/com/eveningoutpost/dexdrip/utils/LibreTrendUtil.java
  app/src/test/java/com/eveningoutpost/dexdrip/Models/ReadingDataTest.java
Labels: device-libre, next-build
