Repository NightscoutFoundation/xDrip, pull requests merged in 2021-12, with the labels that each got.

#1834 No delay for the ascending volume profile
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/AlertPlayer.java
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/pref_notifications.xml
Labels: enhancement, ux-alarm

#1885 DexShareFollow service to support trend as a number and as a string
  app/src/main/java/com/eveningoutpost/dexdrip/ImportedLibraries/dexcom/Dex_Constants.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/sharefollow/RetrofitBase.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/sharefollow/ShareGlucoseRecord.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/sharefollow/ShareTrendDeserializer.java
  app/src/test/java/com/eveningoutpost/dexdrip/cgm/sharefollow/ShareGlucoseRecordTest.java
  wear/src/main/java/com/eveningoutpost/dexdrip/ImportedLibraries/dexcom/Constants.java
  wear/src/main/java/com/eveningoutpost/dexdrip/ImportedLibraries/dexcom/Dex_Constants.java
Labels: sync-dexcom, fix

#1840 Enable override silent mode and force speaker for the 2 existing alarms
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/IdempotentMigrations.java
Labels: enhancement, ux-alarm, next-build, settings

#1888 Update channel selection dependency
  app/src/main/res/xml/xdrip_plus_prefs.xml
Labels: enhancement, next-build, settings
