Repository NightscoutFoundation/xDrip, pull requests merged in 2021-07, with the labels that each got.

#1722 G6 Temperature back
  app/src/main/java/com/eveningoutpost/dexdrip/G5Model/FirmwareCapability.java
  app/src/main/java/com/eveningoutpost/dexdrip/Services/Ob1G5CollectionService.java
Labels: device-dexcom-transmitter, next-build

#1771 Update libre-fix-bt-connection-issues.md
  Documentation/libre-fix-bt-connection-issues.md
Labels: next-build, type-documentation

#1755 Crowdin info
  CONTRIBUTING.md
Labels: code, next-build
