Repository NightscoutFoundation/xDrip, pull requests merged in 2022-02, with the labels that each got.

#1961 Add more logging to help users understand why libre 2 does not communicate with bluetooth.
  app/src/main/java/com/eveningoutpost/dexdrip/ErrorListAdapter.java
  app/src/main/java/com/eveningoutpost/dexdrip/ErrorsActivity.java
  app/src/main/java/com/eveningoutpost/dexdrip/EventLogActivity.java
  app/src/main/java/com/eveningoutpost/dexdrip/Models/BgReading.java
  app/src/main/java/com/eveningoutpost/dexdrip/NFCReaderX.java
  app/src/main/res/layout/activity_stop_sensor.xml
Labels: enhancement, device-libre, logging, next-build

#1975 Keep G6 battery voltage logs for 7 days
  app/src/main/java/com/eveningoutpost/dexdrip/G5Model/Ob1G5StateMachine.java
Labels: enhancement, device-dexcom-transmitter, logging, next-build

#1954 upgrade setup-java and gradle-build actions to v2
  .github/workflows/unit_test.yml
Labels: enhancement, code:quality, next-build, code:java11

#2006 add Estonian language support
  app/src/main/res/values/locales.xml
Labels: enhancement, translation, next-build
