Repository NightscoutFoundation/xDrip, pull requests merged in 2022-06, with the labels that each got.

#2176 Don't allow xDrip to work with OOP2 versions before 1.2 (unless calibrate raw is used)
  app/src/main/java/com/eveningoutpost/dexdrip/NSEmulatorReceiver.java
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/Intents.java
  app/src/main/res/values/strings.xml
Labels: device-libre, fix

#2175 AAPS profile import Log instead of toast message
  app/src/main/java/com/eveningoutpost/dexdrip/profileeditor/ImportAapsProfile.java
Labels: enhancement, ux-notification

#2165 adjust age_adjusted_raw_value for g6
  app/src/main/java/com/eveningoutpost/dexdrip/Models/BgReading.java
Labels: enhancement, algorithmics, next-build

#2186 allow up to two decimal digits for insulin
  app/src/main/java/com/eveningoutpost/dexdrip/Home.java
  app/src/main/java/com/eveningoutpost/dexdrip/PhoneKeypadInputActivity.java
Labels: ui, insulin, fix

#2162 Emphasize Discussions
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  CONTRIBUTING.md
Labels: help, next-build
