Repository NightscoutFoundation/xDrip, pull requests merged in 2022-11, with the labels that each got.

#2312 Aidex support broadcast
  aidex_text.png
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/eveningoutpost/dexdrip/Models/Sensor.java
  app/src/main/java/com/eveningoutpost/dexdrip/receivers/aidex/AidexBroadcastIntents.java
  app/src/main/java/com/eveningoutpost/dexdrip/receivers/aidex/AidexMessageType.java
  app/src/main/java/com/eveningoutpost/dexdrip/receivers/aidex/AidexReceiver.java
  app/src/main/java/com/eveningoutpost/dexdrip/utils/DexCollectionType.java
  app/src/main/res/values/arrays.xml
Labels: enhancement, device-aidex

#1649 Medtronic CareLink Follower (MMConnect for xDrip)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/eveningoutpost/dexdrip/MegaStatus.java
  app/src/main/java/com/eveningoutpost/dexdrip/Models/Treatments.java
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/CollectionServiceStarter.java
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/Constants.java
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/SourceWizard.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/CareLinkDataProcessor.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/CareLinkFollowDownloader.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/CareLinkFollowService.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/client/CareLinkClient.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/client/CountryUtils.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/client/SimpleOkHttpCookieJar.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/ActiveInsulin.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/ActiveNotification.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/Alarm.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/Basal.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/ClearedNotification.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/ConnectData.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/ConnectDataResult.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/Country.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/CountrySettings.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/DataUpload.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/Language.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/Limit.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/Marker.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/MfaRules.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/MonitorData.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/NotificationHistory.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/NumberFormat.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/PostalInfo.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/Profile.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/PumpBannerState.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/RecentData.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/ReportDataProvider.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/ReportDateFormat.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/ReportSnapshotTimelinesForCalendar.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/ReportTimelinesRange.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/Result.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/SensorGlucose.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/SupportedReport.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/TextMap.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/TherapyAlgorithmState.java
  app/src/main/java/com/eveningoutpost/dexdrip/cgm/carelinkfollow/message/User.java
  app/src/main/java/com/eveningoutpost/dexdrip/utils/DexCollectionHelper.java
  app/src/main/java/com/eveningoutpost/dexdrip/utils/DexCollectionType.java
  app/src/main/java/com/eveningoutpost/dexdrip/utils/Preferences.java
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/pref_data_source.xml
Labels: enhancement, sync

#2361 Dexcom clarifications
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/SourceWizard.java
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, settings

#2293 Code cleanup - home menu event handlers
  app/src/main/java/com/eveningoutpost/dexdrip/Home.java
  app/src/main/res/menu/menu_home.xml
Labels: enhancement, code:quality, next-build
