Repository NightscoutFoundation/xDrip, pull requests merged in 2022-05, with the labels that each got.

#2098 No, don't use for calibration
  app/src/main/java/com/eveningoutpost/dexdrip/Home.java
Labels: calibration, fix

#2107 System Status cleanup
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/eveningoutpost/dexdrip/MegaStatus.java
  app/src/main/java/com/eveningoutpost/dexdrip/SystemStatus.java
  app/src/main/res/layout/activity_system_status.xml
  app/src/main/res/menu/menu_system_status.xml
Labels: enhancement, ui, code:quality

#2114 Further fixes for #1781 (preference search exceptions)
  app/src/main/res/xml/pref_advanced_settings.xml
  app/src/main/res/xml/pref_data_source.xml
  app/src/main/res/xml/pref_data_sync.xml
  app/src/main/res/xml/pref_general.xml
  app/src/main/res/xml/pref_notifications.xml
  app/src/main/res/xml/xdrip_plus_prefs.xml
Labels: settings, fix

#2127 Make sure that xDrip will not crash in the case that parsing a trade or history sensor will fail.
  app/src/main/java/com/eveningoutpost/dexdrip/NFCReaderX.java
Labels: device-libre, next-build, fix
