Repository NightscoutFoundation/xDrip, pull requests merged in 2022-01, with the labels that each got.

#1788 Capitalize "Disable alert" on the alert edit screen
  app/src/main/res/values/strings.xml
Labels: translation, next-build

#1880 Android studio refactor of the code + fix of a trivial bug from my latest commit.
  app/src/main/java/com/eveningoutpost/dexdrip/LibreAlarmReceiver.java
  app/src/main/java/com/eveningoutpost/dexdrip/Models/GlucoseData.java
  app/src/main/java/com/eveningoutpost/dexdrip/Models/LibreOOPAlgorithm.java
  app/src/main/java/com/eveningoutpost/dexdrip/NFCReaderX.java
  app/src/main/java/com/eveningoutpost/dexdrip/NSEmulatorReceiver.java
  app/src/main/java/com/eveningoutpost/dexdrip/utils/LibreTrendPoint.java
  app/src/main/java/com/eveningoutpost/dexdrip/utils/LibreTrendUtil.java
Labels: device-libre, algorithmics, code:quality, next-build

#1897 Discussions before issues and PRs
  .github/ISSUE_TEMPLATE/config.yml
  CONTRIBUTING.md
  README.md
Labels: code:quality, next-build

#1856 "when" is very confusing, as people usually respond "x minutes ago". …
  app/src/main/res/values/strings.xml
Labels: enhancement, ui, translation, next-build

#1926 Update google truth
  app/build.gradle
  app/src/test/java/com/eveningoutpost/dexdrip/Models/ForecastTest.java
  wear/build.gradle
Labels: enhancement, code:quality, next-build

#1899 execute unit tests just once
  .github/workflows/unit_test.yml
Labels: code:quality

#1767 add unit gram (g) to carb input activities
  app/src/main/java/com/eveningoutpost/dexdrip/Home.java
  app/src/main/java/com/eveningoutpost/dexdrip/Models/Treatments.java
  app/src/main/java/com/eveningoutpost/dexdrip/PhoneKeypadInputActivity.java
  wear/src/main/java/com/eveningoutpost/dexdrip/KeypadInputActivity.java
  wear/src/main/java/com/eveningoutpost/dexdrip/Models/Treatments.java
Labels: enhancement, ui, next-build

#1674 fix: make it possible to translate all xdrip preferences
  app/src/main/java/com/eveningoutpost/dexdrip/Home.java
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/xdrip_plus_prefs.xml
Labels: translation, code:quality, next-build

#1955 G6 backfill prior to start AAPS fix copied to wear
  wear/src/main/java/com/eveningoutpost/dexdrip/G5Model/Ob1G5StateMachine.java
  wear/src/main/java/com/eveningoutpost/dexdrip/Models/BgReading.java
  wear/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/BroadcastGlucose.java
Labels: sync, next-build, fix

#1879 fix for Unparseable date format
  app/build.gradle
  app/src/main/java/com/eveningoutpost/dexdrip/Models/DateUtil.java
  app/src/test/java/com/eveningoutpost/dexdrip/Models/DateUtilTest.java
  wear/build.gradle
Labels: sync-nightscout, next-build, fix
