Repository NightscoutFoundation/xDrip, pull requests merged in 2022-07, with the labels that each got.

#2164 Add Range Settings to the first statistics page
  app/src/main/java/com/eveningoutpost/dexdrip/stats/FirstPageFragment.java
  app/src/main/res/layout/stats_general.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, next-build

#2004 Broadcast service (add a simple API to communicate with thirdparty applications)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/eveningoutpost/dexdrip/NewDataObserver.java
  app/src/main/java/com/eveningoutpost/dexdrip/Services/MissedReadingService.java
  app/src/main/java/com/eveningoutpost/dexdrip/Services/broadcastservice/BroadcastEntry.java
  app/src/main/java/com/eveningoutpost/dexdrip/Services/broadcastservice/BroadcastService.java
  app/src/main/java/com/eveningoutpost/dexdrip/Services/broadcastservice/Const.java
  app/src/main/java/com/eveningoutpost/dexdrip/Services/broadcastservice/models/BroadcastModel.java
  app/src/main/java/com/eveningoutpost/dexdrip/Services/broadcastservice/models/GraphLine.java
  app/src/main/java/com/eveningoutpost/dexdrip/Services/broadcastservice/models/GraphPoint.java
  app/src/main/java/com/eveningoutpost/dexdrip/Services/broadcastservice/models/Settings.java
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/AlertPlayer.java
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/Notifications.java
  app/src/main/java/com/eveningoutpost/dexdrip/utils/Preferences.java
  app/src/main/java/com/eveningoutpost/dexdrip/xdrip.java
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/pref_advanced_settings.xml
Labels: enhancement, sync, next-build

#2214 Configurable text color for high-, in-range- and low-clucose values
  app/src/main/java/com/eveningoutpost/dexdrip/BestGlucose.java
  app/src/main/java/com/eveningoutpost/dexdrip/Home.java
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/ColorCache.java
  app/src/main/java/com/eveningoutpost/dexdrip/xDripWidget.java
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/xdrip_plus_prefs.xml
Labels: enhancement, ui, next-build
