Repository NightscoutFoundation/xDrip, pull requests merged in 2022-09, with the labels that each got.

#2296 Alerts: fix custom sound handling
  app/src/main/java/com/eveningoutpost/dexdrip/AlertList.java
  app/src/main/java/com/eveningoutpost/dexdrip/EditAlertActivity.java
  app/src/main/java/com/eveningoutpost/dexdrip/Models/JoH.java
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/AlertPlayer.java
  app/src/main/res/values/strings.xml
Labels: settings, fix

#2295 Decommission "lower fuzzer"
  app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/BgGraphBuilder.java
  app/src/main/java/com/eveningoutpost/dexdrip/utils/Preferences.java
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/xdrip_plus_prefs.xml
Labels: code:quality, next-build, settings

#2302 Bugfix - correcting highlighting glitch in Home dropdown menu
  app/src/main/res/layout/activity_home.xml
Labels: enhancement, ui, next-build

#2343 Add Transmitter end of life message dialog
  app/src/main/java/com/eveningoutpost/dexdrip/StartNewSensor.java
  app/src/main/java/com/eveningoutpost/dexdrip/ui/dialog/G6EndOfLifeDialog.java
  app/src/main/res/values/strings.xml
Labels: enhancement, ux-notification, device-dexcom-transmitter
